### ISSUE TITLE
ORC Format Parsing – Out-of-Bounds Access in Protobuf Messages

### ISSUE THREAD

**Issue by HeenaBansal2009** [apache/orc#1021]
what happens if type.fieldnames_size()  is less than the type.subtypes_size(). The type.fieldnames(i) will be invalid access. 

File name :  TypeImpl.cc
```
case proto::Type_Kind_STRUCT: {
TypeImpl* result = new TypeImplSTRUCT);
uint64_t size = static_cast<uint64_t>(type.subtypes_size());
std::vector<Type*> typeList(size);
std::vector<std::string> fieldList(size);
for(int i=0; i < type.subtypes_size(); ++i)
{ result->addStructField(type.fieldnames(i), convertType(footer.types(static_cast<int> (type.subtypes(i))),footer)); }
return std::unique_ptr<Type>(result);
```
I reproduced the scenario by modifying c++/test/TestType.cc (refer screenshot) and it crashed.(refer output screenshot
<img width="1491" alt="Screen Shot 2022-01-19 at 12 33 21 PM" src="https://user-images.githubusercontent.com/86018844/150183885-6ad98a50-bbb0-43ee-b0fe-8e4692f92ae7.png">
)

<img width="1386" alt="Screen Shot 2022-01-19 at 12 32 29 PM" src="https://user-images.githubusercontent.com/86018844/150183721-4fb5f191-39a4-4f89-b5cc-57e08a6bae7b.png">

**Comment by dongjoon-hyun** [comment]
Thank you, @HeenaBansal2009 . Are you interested in making a PR?

**Comment by HeenaBansal2009** [comment]
Thanks @dongjoon-hyun . Sure ill raise a PR soon.

**Comment by HeenaBansal2009** [comment]
HI @dongjoon-hyun , I am unable to push the changes to apache/orc.git. Anything you can help here . 

$  git push --set-upstream origin Out-of-Bounds-Access-in-Protobuf-Messages
Warning: Permanently added the ECDSA host key for IP address '140.82.114.4' to the list of known hosts.
ERROR: Permission to apache/orc.git denied to HeenaBansal2009.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ git remote -v 
origin	git@github.com:apache/orc.git (fetch)
origin	git@github.com:apache/orc.git (push)
