### ISSUE TITLE
Where can I find sample code for using ORC column encryption when writing ORC files with spark dataSource

### ISSUE THREAD

**Issue by liujinhui1994** [apache/orc#1050]
Where can I find sample code for using ORC column encryption when writing ORC files with spark dataSource

**Comment by dongjoon-hyun** [comment]
Did you check Apache ORC webpage about Spark Configuration, @liujinhui1994 ? The encryption option should be provided in the same way during writing and reading. So, we prefer to put it to the table properties.

- https://orc.apache.org/docs/spark-config.html
```
CREATE TABLE encrypted (
  ssn STRING,
  email STRING,
  name STRING
)
USING ORC
OPTIONS (
  hadoop.security.key.provider.path "kms://http@localhost:9600/kms",
  orc.key.provider "hadoop",
  orc.encrypt "pii:ssn,email",
  orc.mask "nullify:ssn;sha256:email"
)
```

**Comment by liujinhui1994** [comment]
I checked here. Only saw how the table is configured. There is no way to see the datasource. Because my task will not use the table.
Does the above configuration work the way dataSource does?

@dongjoon-hyun

**Comment by guiyanakuang** [comment]
@liujinhui1994 Using a custom dataSource to read and write orc files?
Maybe this test case can help you.
https://github.com/apache/orc/blob/main/java/core/src/test/org/apache/orc/impl/TestEncryption.java

**Comment by liujinhui1994** [comment]
Is it possible to do something like parquet encryption.
The following way to pass?
JavaSparkContext jsc = new JavaSparkContext(spark.sparkContext());
jsc.hadoopConfiguration().set("","")  

@guiyanakuang

**Comment by liujinhui1994** [comment]
https://spark.apache.org/docs/latest/sql-data-sources-parquet.html

**Comment by guiyanakuang** [comment]
I think it's similar, but I haven't practiced using it this way

**Comment by liujinhui1994** [comment]
ok i'll try it  thanks @guiyanakuang

**Comment by dongjoon-hyun** [comment]
Yep. That's the test case which I wrote in the Spark community. :)
Thanks, @guiyanakuang . I'll close this issue because it seems that @liujinhui1994 found the answer here.
