### ISSUE TITLE
Readme still says cpp only writes version 0.11?

### ISSUE THREAD

**Issue by XinyuZeng** [apache/orc#1052]
The readme says that c++ version only writes version 0.11 but from https://github.com/apache/orc/blob/cf720d7b2333618c652445299486cb9600bdbe4f/c%2B%2B/src/Writer.cc#L47

it seems that the default has already changed to 0.12

**Comment by dongjoon-hyun** [comment]
Thank you for the reporting. Ya, there might be mismatch between the documentation and code.

Could you confirm this, @wgtmac and @stiga-huang ?

**Comment by wgtmac** [comment]
> Thank you for the reporting. Ya, there might be mismatch between the documentation and code.
> 
> Could you confirm this, @wgtmac and @stiga-huang ?

I can confirm that the README is outdated about this. Thanks @XinyuZeng for reporting.

**Comment by XinyuZeng** [comment]
I created a PR #1054 regarding this.
