### ISSUE TITLE
Padding length   and Padding ratio What does it stand for?If there's a number on it, does it affect the program from reading this file,

### ISSUE THREAD

**Issue by liangrui1988** [apache/orc#1083]
Padding length   and Padding ratio What does it stand for?If there's a number on it, does it affect the program from reading this file,
```
File length: 548692248 bytes
Padding length: 2381182 bytes
Padding ratio: 0.43%
```
When spark read the orC zlib file, it was sometimes stuck for more than half an hour, but we didn't know whether the file was not written

**Comment by dongjoon-hyun** [comment]
Hi, @liangrui1988 . Please refer ORC spec in our official website.

![](https://orc.apache.org/img/OrcFileLayout.png)

Here is the formula we use. It exists simply to match the underlying file system's block size historically. If you are using S3, your program will not read that part at all. So, there is no impact in the modern cloud infra.

https://github.com/apache/orc/blob/6b053d4ba4df036e2691f84331bd407354a7c3b2/java/tools/src/java/org/apache/orc/tools/FileDump.java#L771-L780

**Comment by liangrui1988** [comment]
Mine is a private cluster deployment, on disk, will this matter?Does it affect the application's ability to read the file?

**Comment by liangrui1988** [comment]
Does reading and writing different versions of ORC matter?For example, 1.5.12 to write files, 1.5.5 to read files?thank you

**Comment by dongjoon-hyun** [comment]
Sorry but why don't you test your actual private cluster? We have no recommendations for private cluster deployments because we don't know what you are using it, @liangrui1988 .

**Comment by liangrui1988** [comment]
This is caused by the ORC parameter problem, not the cluster problem. The writer reduces the stripe of the ORC and restores it to 256MB.

**Comment by dongjoon-hyun** [comment]
Could you provide some reproducible example, @liangrui1988 ?
