### ISSUE TITLE
Broken Avatar images in Apache ORC News

### ISSUE THREAD

**Issue by dongjoon-hyun** [apache/orc#1092]
It seems that we have broken images at the following pages.

- https://orc.apache.org/news/2022/03/05/add-quanlong/
- https://orc.apache.org/news/2022/04/15/ORC-1.7.4/

**Comment by dongjoon-hyun** [comment]
Maybe, is ASF Home machine still inaccessible to you, @wgtmac and @williamhyun ?

**Comment by wgtmac** [comment]
@dongjoon-hyun I have tried to set up the page, but failed. Do you have any guideline to proceed? Thanks!

**Comment by williamhyun** [comment]
@dongjoon-hyun Yes, I cannot access home.apache.org via sftp. 

- https://home.apache.org/~william

**Comment by dongjoon-hyun** [comment]
@wgtmac and @williamhyun .

1. According to https://infra.apache.org, they decommissioned the old server.
2. New machine is `home-lw-us (207.244.88.131)` whose aliases are `people.apache.org` and `home.apache.org`.
   - https://infra.apache.org/machines.html
3. The new server is supposed to serve `SFTP` connection.
   - https://infra.apache.org/committers.html#machines
> Committers may access home.apache.org. See the related information in the [New committers' guide](https://infra.apache.org/new-committers-guide.html). Note that you do only have sftp access. There is no shell access. RSA SSH keys are required for sftp access, which you can update via [Whimsy](https://whimsy.apache.org/) or [id.apache.org](https://id.apache.org/).

If you guys cannot access it, it seems that we need to file an INFRA jira issue for you.

**Comment by dongjoon-hyun** [comment]
Here is the INFRA JIRA.
- https://issues.apache.org/jira/browse/INFRA-23185

**Comment by dongjoon-hyun** [comment]
Hi, @wgtmac and @williamhyun . According to the INFRA team's comment, please try to connect your home again.
> I have corrected the host attribute for "william." We do not have an ASF ID "wgtmac" but I'm guessing you meant "gangwu".. That person already has the home.apache.org host attribute, so they should be able to SFTP in.

**Comment by williamhyun** [comment]
It works!
```
% sftp home.apache.org
Connected to home.apache.org.
sftp> ls
```

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun . I confirmed that your news is recovered.
- https://orc.apache.org/news/2022/04/15/ORC-1.7.4/

**Comment by dongjoon-hyun** [comment]
Gentle ping, @wgtmac . INFRA team is waiting for your confirmation. Please comment on INFRA JIRA.

**Comment by wgtmac** [comment]
Thanks @dongjoon-hyun. I have the access now. But how can I upload my avatar?

**Comment by dongjoon-hyun** [comment]
It's a traditional personal website hosting way in Apache Home account, @wgtmac .

1. To simply put, your `https://people.apache.org/~gangwu` is mapped to `public_html` under your home directory.

2. Apache ORC website expects `https://people.apache.org/~gangwu/gangwu.png`.

3. To achieve the above item (2), download your GitHub image and rename it to your Apache ID, `gangwu.png`.
```
curl -LO https://avatars.githubusercontent.com/u/4684607
https://avatars.githubusercontent.com/u/4684607
```

4. Finally, you need to connect to the server and do the following.
```
mkdir public_html
cd public_html
put gangwu.png
```

**Comment by wgtmac** [comment]
> It's a traditional personal website hosting way in Apache Home account, @wgtmac .
> 
> 1. To simply put, your `https://people.apache.org/~gangwu` is mapped to `public_html` under your home directory.
> 2. Apache ORC website expects `https://people.apache.org/~gangwu/gangwu.png`.
> 3. To achieve the above item (2), download your GitHub image and rename it to your Apache ID, `gangwu.png`.
> 
> ```
> curl -LO https://avatars.githubusercontent.com/u/4684607
> ```
> 
> 4. Finally, you need to connect to the server via `sftp` and do the following.
> 
> ```
> mkdir public_html
> cd public_html
> put gangwu.png
> ```

Awesome! Thanks @dongjoon-hyun for the help!

**Comment by dongjoon-hyun** [comment]
Thank you, @wgtmac and @williamhyun . I confirmed that both broken links are fixed.
