### ISSUE TITLE
ORC-1188: Fix `ORC_PREFER_STATIC_ZLIB`

### ISSUE THREAD

**Issue by loqs** [apache/orc#1138]
https://github.com/apache/orc/blob/1e2962064b209f1b00188877f08d4226da85c640/cmake_modules/ThirdpartyToolchain.cmake#L147-L151
If ```ORC_PREFER_STATIC_ZLIB``` is false then the static system zlib is used.
If ```ORC_PREFER_STATIC_ZLIB``` is true and ```ZLIB_STATIC_LIB``` is set then the shared system zlib is used.
This usage contradicts the description for ```ORC_PREFER_STATIC_ZLIB``` 'Prefer static zlib library, if available'.

**Comment by dongjoon-hyun** [comment]
Thank you for reporting, @loqs . Do you want to make a PR?

**Comment by dongjoon-hyun** [comment]
cc @stiga-huang and @wgtmac too

**Comment by dongjoon-hyun** [comment]
ORC_PREFER_STATIC_ZLIB seems to be added at Apache ORC 1.7.0. 
I filed ORC-1188 and set Milestone 1.7.5.

**Comment by dongjoon-hyun** [comment]
Okay, let me make a PR for this.
