### ISSUE TITLE
Pin `org.jetbrains.annotations` dependency

### ISSUE THREAD

**Issue by dongjoon-hyun** [apache/orc#1176]
During preparing 1.8.0, I realized that we had better pin `annotations` library to minimize downstream projects' migration burden.

https://github.com/dongjoon-hyun/spark/pull/4/files#

```
      <dependency>
        <groupId>org.jetbrains</groupId>
        <artifactId>annotations</artifactId>
        <version>23.0.0</version>
      </dependency>
```

**Comment by williamhyun** [comment]
Sure @dongjoon-hyun , I will take a look.

**Comment by dongjoon-hyun** [comment]
Thank you again, @williamhyun .
