### ISSUE TITLE
Apache ORC website revamp

### ISSUE THREAD

**Issue by williamhyun** [apache/orc#1197]
- Increase page width and improve resizing
- Create `RELEASES` menu
- Menu reordering
- Adjust Footer

**Comment by dongjoon-hyun** [comment]
+100! :)

**Comment by dongjoon-hyun** [comment]
BTW, is this aiming new theme with the existing `jekyll`? Or, switching framework itself?

**Comment by dongjoon-hyun** [comment]
I quickly checked some of our downstream projects.

| ASF Project  | Tools | Homepage |
| ------------- | ------------- | -- |
| Apache Spark | [Jekyll](https://github.com/apache/spark/blob/master/docs/_config.yml#L4) | https://spark.apache.org |
| Apache Flink | [Hugo](https://github.com/apache/flink/blob/5c87b69b5300e8678629aa8b769d60ec2fdbf3d1/.github/workflows/docs.sh#L26) | https://flink.apache.org |
| Apache Iceberg | [MkDocs](https://www.mkdocs.org) | https://iceberg.apache.org |

**Comment by dongjoon-hyun** [comment]
I have no preference. You can choose what you need at all levels.

**Comment by williamhyun** [comment]
Thank you for doing the research! 
I am still looking into which tool to utilize for our upcoming website.

By the way, I realized that it would be greatly helpful to us if we published the pre-built Apache ORC Developer-environment Docker images such as `site/Dockerfile` and `docker/debian11/Dockerfile` following the Apache Arrow community.
- https://hub.docker.com/r/apache/arrow-dev/tags

What do you guys think about making a Docker image for devs?

**Comment by dongjoon-hyun** [comment]
+1 for Apache ORC DockerHub.

**Comment by dongjoon-hyun** [comment]
It seems that https://github.com/apache/orc/issues/1207 is resolved successfully. Please let me know if you need my help for this issue.
