### ISSUE TITLE
Setup DockHub repo `apache/orc-dev` 

### ISSUE THREAD

**Issue by dongjoon-hyun** [apache/orc#1207]
- [x] Create `apache/orc-dev` via https://issues.apache.org/jira/browse/INFRA-23534
  - https://hub.docker.com/r/apache/orc-dev/tags
- [x] Publish `docker` test images to `apache/orc-dev`.
- [x] Publish `site` build image to `apache/orc-dev`.
- [x] Update Apache ORC website.
  - https://github.com/apache/orc/pull/1211
- [x] Update `docker` script
  - https://github.com/apache/orc/pull/1212

**Comment by dongjoon-hyun** [comment]
Hi, @williamhyun . I created this. While waiting your account setup, I'll try to upload some.

**Comment by dongjoon-hyun** [comment]
Since I was the only one who has a write permission, I published the initial set of images.
- https://hub.docker.com/r/apache/orc-dev/tags

You can publish Apache ORC website docker image there in order to verify your write permission after you accepted the invitation.

**Comment by williamhyun** [comment]
Thank you for letting me know! 
I was able to publish the ORC website docker image. 

- https://hub.docker.com/r/apache/orc-dev/tags

**Comment by dongjoon-hyun** [comment]
Could you update the existing scripts and README.md to use the new pre-built images, please, @williamhyun ?

**Comment by williamhyun** [comment]
Sure!

**Comment by dongjoon-hyun** [comment]
I merged #1211 and #1212 . I believe we can close this issue as 'Done'.
