### ISSUE TITLE
ORC-1257: Publish multi-architecture ORC-dev docker images

### ISSUE THREAD

**Issue by williamhyun** [apache/orc#1228]
**BEFORE**
<img width="650" alt="Screen Shot 2022-08-19 at 6 29 30 PM" src="https://user-images.githubusercontent.com/62487364/185724194-904cf522-47a9-4ca1-9096-83e4bd836da9.png">

**AFTER**
<img width="650" alt="Screen Shot 2022-08-19 at 6 29 24 PM" src="https://user-images.githubusercontent.com/62487364/185724187-4280bcb3-3815-4a17-94da-fb717b0f7748.png">

**Comment by williamhyun** [comment]
cc: @dongjoon-hyun 
I'm rebuilding the docker images in order to publish in the multi-architecture format.

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun !

**Comment by dongjoon-hyun** [comment]
Hi, @williamhyun . Is this finished?

**Comment by dongjoon-hyun** [comment]
I saw that you finished mostly. Let me finish the following remaining variant images and close this issue for Apache ORC 1.8.0. :)
- `debian10_jdk-11`
- `ubuntu20_jdk-11`
- `ubuntu20_jdk-11_cc-clang`
- `fedora37`
<img width="573" alt="Screen Shot 2022-08-28 at 8 33 48 PM" src="https://user-images.githubusercontent.com/9700541/187117869-5d1a5d28-6388-42e5-b35f-80026267992d.png">
.

**Comment by dongjoon-hyun** [comment]
Now, all images are published as `multi-architecture` images. Thank you!
