### ISSUE TITLE
Is it time to enable c++17 to the C++ library?

### ISSUE THREAD

**Issue by wgtmac** [apache/orc#1294]
At the moment, the C++ library supports gcc, clang and msvc compilers at the same time with C++11 enabled. To keep up with the pace of modern c++ standards, we can enable c++17 or even c++20 by default. We should be careful with public headers as they are dependent by various downstream projects. Elsewhere we can enjoy new language features internally in the library.

However, this requires us to lift the minimum versions supported for the compilers listed below:
- gcc: at least gcc5 is required (https://gcc.gnu.org/projects/cxx-status.html#cxx17)
- clang: at least clang5 is required (https://clang.llvm.org/cxx_status.html#cxx17)
- msvc: at least Visual Studio 2017 version 15.3 (https://learn.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170#c-standards-support)

Thoughts? @dongjoon-hyun @williamhyun @guiyanakuang @stiga-huang @coderex2522

**Comment by dongjoon-hyun** [comment]
+1 for Apache ORC 1.9.0.

**Comment by dongjoon-hyun** [comment]
This is resolved via https://github.com/apache/orc/pull/1295
