### ISSUE TITLE
Byte to integer conversions fail on platforms with unsigned char type

### ISSUE THREAD

**Issue by johnwheffner** [apache/orc#1318]
When building the C++ library on a platform where `char` is by default unsigned, byte-to-integer expansion is incorrect in `orc::expandBytesToIntegers` as well as in a few unit tests.

This can be reproduced on any CPU architecture when building with gcc by compiling with `-funsigned-char`.

**Comment by dongjoon-hyun** [comment]
Thank you, @johnwheffner and @wgtmac .

**Comment by dongjoon-hyun** [comment]
FYI. Apache ORC 1.8.1 is scheduled on December 3rd.

cc @williamhyun

**Comment by wgtmac** [comment]
> Thank you, @johnwheffner and @wgtmac . For now, I set the milestone 1.9.0, but we can backport it to [Milestone 1.8.1](https://github.com/apache/orc/milestone/13).

I can confirm that this issue only exists in the main branch, therefore we don't need backport the fix to branch-1.8.

**Comment by dongjoon-hyun** [comment]
It's great. Thank you for the confirmation, @wgtmac .

**Comment by wgtmac** [comment]
@johnwheffner FYI, this issue has been fixed in the main branch. Please let me know if there is any remaining issue. Thanks!
