### ISSUE TITLE
[C++] Behavior mismatch with option useTightNumericVector

### ISSUE THREAD

**Issue by ffacs** [apache/orc#1448]
With the option useTightNumericVector, the typeImpl would return a byteVectorBatch
https://github.com/apache/orc/blob/5ed1bbe7b63d288b0924f8adcdae4423f4a5f420/c%2B%2B/src/TypeImpl.cc#L285-L294

however, BooleanColumnReader and BooleanColumnWriter only accept LongVectorBatch

https://github.com/apache/orc/blob/5ed1bbe7b63d288b0924f8adcdae4423f4a5f420/c%2B%2B/src/ColumnWriter.cc#L670-L675

https://github.com/apache/orc/blob/5ed1bbe7b63d288b0924f8adcdae4423f4a5f420/c%2B%2B/src/ColumnReader.cc#L169-L177

**Comment by dongjoon-hyun** [comment]
Thank you for reporting. Are you interesting in making a PR, @ffacs ?

**Comment by ffacs** [comment]
> Thank you for reporting. Are you interesting in making a PR, @ffacs ?

I would make a PR later.

**Comment by wgtmac** [comment]
I close this issue as the PR has been merged. Feel free to reopen if there is any remaining work.
