### ISSUE TITLE
Is it time to remove support for Ubuntu 18.04?

### ISSUE THREAD

**Issue by deshanxiao** [apache/orc#1464]
Ubuntu 18.04 LTS will reach the end of its hardware and maintenance update LTS support window on April 30, 2023.

**Comment by dongjoon-hyun** [comment]
Thank you, @deshanxiao .

+1 for the proposal.

For the other people, here is https://ubuntu.com/about/release-cycle , 

![Screen Shot 2023-04-11 at 10 43 15 AM](https://user-images.githubusercontent.com/9700541/231245376-3f1cdcf7-966f-4841-9ea8-93283311880e.png)

I believe we can ignore `Extended Security Maintenance (ESM)` period.

**Comment by dongjoon-hyun** [comment]
Also, cc @williamhyun and @wgtmac too

**Comment by wgtmac** [comment]
+1 on dropping it. Thanks!
