### ISSUE TITLE
c++ code doesn't compile with gcc13

### ISSUE THREAD

**Issue by smahapatra1** [apache/orc#1489]
I tried to compile orc 1.8.3 with c++ 20 and gcc 13, but got ColumnReader.cc didn't compile. I had to get around the problem by using -Wno-dangling-reference in the command line, but the code should be fixed or correct pragma should be used.

https://gcc.gnu.org/onlinedocs/gcc-13.1.0/gcc/C_002b_002b-Dialect-Options.html#index-Wdangling-reference

**Comment by dongjoon-hyun** [comment]
cc @wgtmac , @stiga-huang

**Comment by wgtmac** [comment]
@smahapatra1 Could you please share more information about your environment? Thanks!

**Comment by dongjoon-hyun** [comment]
Thank you for reporting. 

According to the website, GCC 13 seems too new to be adopted in popular OS releases and GitHub Action environment.
- https://gcc.gnu.org

If you don't mind, shall we wait and revisit in a few months, @smahapatra1 .

**Comment by dongjoon-hyun** [comment]
I included this in Apache ORC 2.0.0 milestone. Let me take a look at this.

**Comment by dongjoon-hyun** [comment]
@smahapatra1 and @wgtmac .

As of today, I can confirm that `Apache ORC 2.0.0` supports `GCC 13.2.0`. Here is the community CI with `Ubuntu 24.04`.

- https://github.com/apache/orc/actions/workflows/build_and_test.yml
```
$ docker run -it --rm apache/orc-dev:ubuntu24 gcc --version
gcc (Ubuntu 13.2.0-9ubuntu1) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

- https://github.com/apache/orc/actions/runs/7313584824/job/19925328137
```
Status: Downloaded newer image for apache/orc-dev:ubuntu24
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
```

**Comment by wgtmac** [comment]
Thanks for checking! @dongjoon-hyun
