### ISSUE TITLE
Multi streams optimization under indexing?

### ISSUE THREAD

**Issue by deshanxiao** [apache/orc#1516]
In ORC Spec:
> For columns with multiple streams, the sequences of positions in each stream are concatenated. That was an unfortunate decision on my part that we should fix at some point, because it makes code that uses the indexes error-prone.

ORC v2.0 will be a good opportunity to solve the issue.

cc @dongjoon-hyun @wgtmac @guiyanakuang @pavibhai

**Comment by wgtmac** [comment]
Do you have any proposal?

**Comment by deshanxiao** [comment]
> Do you have any proposal?

Yes, I will add it here in a few days.

**Comment by pavibhai** [comment]
> Yes, I will add it here in a few days.

If it makes sense. I would recommend that we also pen down the specific challenges that arise from this to ensure that we have addressed all of these with the proposal.

**Comment by dongjoon-hyun** [comment]
Well, it's possible, but I don't think it's worth to try in Apache ORC 2.0.0.
Basically, I hope we can split Apache ORC Format Version from Apache ORC Library Version like Apache Arrow or Apache Parquet project.

**Comment by deshanxiao** [comment]
Thank you @dongjoon-hyun . Please let me know once we start to split the ORC Format.
