### ISSUE TITLE
Release Apache ORC 1.8.4

### ISSUE THREAD

**Issue by guiyanakuang** [apache/orc#1528]
- [x] GitHub Action CI Check (Java 8/11/17) and `Ubuntu`/`MacOS`/`Windows`.
   - https://github.com/apache/orc/actions/workflows/build_and_test.yml?query=branch%3Abranch-1.8
- [x] Docker Tests (CentOS7, Debian10/11, Ubuntu18/20/22, Fedora37)

```bash
./run-all.sh apache branch-1.8
Launching centos7 as 5870
Launching debian10 as 5871
Launching debian11 as 5872
Launching ubuntu18 as 5873
Launching ubuntu20 as 5874
Launching ubuntu22 as 5875
Launching fedora37 as 5876
Launching debian10_jdk=11 as 5877
Launching ubuntu20_jdk=11 as 5878
Launching ubuntu20_jdk=11_cc=clang as 5879
Waiting for 5870
Waiting for 5871
Waiting for 5872
Waiting for 5873
Waiting for 5874
Waiting for 5875
Waiting for 5876
Waiting for 5877
Waiting for 5878
Waiting for 5879

Test start: Sat Jun 10 13:58:39 CST 2023
End: Sat Jun 10 14:58:04 CST 2023

tail -n5 logs/*test*
==> logs/centos7-test.log <==
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 931.69 sec
Built target test-out
Finished centos7 at Sat Jun 10 14:50:22 CST 2023

==> logs/debian10-test.log <==
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 819.60 sec
Built target test-out
Finished debian10 at Sat Jun 10 14:55:39 CST 2023

==> logs/debian10_jdk=11-test.log <==
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 830.01 sec
Built target test-out
Finished debian10_jdk=11 at Sat Jun 10 14:56:34 CST 2023

==> logs/debian11-test.log <==
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 810.52 sec
Built target test-out
Finished debian11 at Sat Jun 10 14:55:52 CST 2023

==> logs/fedora37-test.log <==
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 755.56 sec
Built target test-out
Finished fedora37 at Sat Jun 10 14:57:46 CST 2023

==> logs/ubuntu18-test.log <==
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 833.13 sec
Built target test-out
Finished ubuntu18 at Sat Jun 10 14:55:55 CST 2023

==> logs/ubuntu20-test.log <==
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 711.93 sec
Built target test-out
Finished ubuntu20 at Sat Jun 10 14:57:48 CST 2023

==> logs/ubuntu20_jdk=11-test.log <==
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 696.43 sec
Built target test-out
Finished ubuntu20_jdk=11 at Sat Jun 10 14:58:04 CST 2023

==> logs/ubuntu20_jdk=11_cc=clang-test.log <==
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 851.49 sec
Built target test-out
Finished ubuntu20_jdk=11_cc=clang at Sat Jun 10 14:53:56 CST 2023

==> logs/ubuntu22-test.log <==
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 733.78 sec
Built target test-out
Finished ubuntu22 at Sat Jun 10 14:57:14 CST 2023
```

- [X] [Apache Spark 3.4.1 Integration Test with 1.8.4 SNAPSHOT](https://github.com/guiyanakuang/spark/pull/1)
- [X] [Apache Iceberg 1.2.1 Integration Test with 1.8.4 SNAPSHOT](https://github.com/guiyanakuang/iceberg/pull/50)
- [x] Vote Tag Creation
- [x] Upload RC0 Vote Artifacts
- [x] Send RC0 Vote Email
- [x] [Apache Spark 3.4.1 Integration Integration Test with RC0](https://github.com/guiyanakuang/spark/pull/2)
- [x] [Apache Iceberg 1.2.1 Integration Test with RC0](https://github.com/guiyanakuang/iceberg/pull/51)
- [x] Send RC0 Vote Result
- [x] Publish to Apache Download
- [x] Release Tag Creation
- [x] Publish to Maven Central
- [x] Create next milestone
- [x] Register `1.8.4` to https://reporter.apache.org/addrelease.html?orc 

**I plan to start the Release Candidate (RC) voting for Apache ORC 1.8.4 on June 11th, 2023.**

**Comment by dongjoon-hyun** [comment]
Thank you for making this issue, @guiyanakuang .

**Comment by dongjoon-hyun** [comment]
Thank you so much for updating the progress and RC1 vote.

**Comment by guiyanakuang** [comment]
Hey @dongjoon-hyun, I have a question, I generated the API docs for 1.8.4. Then I updated it to the asf-site branch. The tutorial then updated the API docs to the main branch as well.

Shouldn't we update in branch-1.8, is it wrong to update to the main branch?

**Comment by dongjoon-hyun** [comment]
BTW, Maven Central is synced with Apache Repo. Could you make a PR to Apache Spark and ping me? Also, you can make a PR to Apache Iceberg too.
- https://repo1.maven.org/maven2/org/apache/orc/orc-core/1.8.4/

**Comment by dongjoon-hyun** [comment]
If you are busy, I can do that for you, but I encourage you to contribute to Apache Spark community too as the Apache ORC release manager. ;)

**Comment by guiyanakuang** [comment]
> BTW, Maven Central is synced with Apache Repo. Could you make a PR to Apache Spark and ping me? Also, you can make a PR to Apache Iceberg too.
> 
> * https://repo1.maven.org/maven2/org/apache/orc/orc-core/1.8.4/

Sure, later I will submit a pr for the upgrade ORC

**Comment by guiyanakuang** [comment]
> You did correctly. We don't commit the generated docs to the `branch-1.8`. Likewise, we also don't commit the generated docs to the `branch-1.7` either.
> 
> The main reason is that Apache ORC only keeps one API docs in our website. Moreover, after I release Apache ORC 1.9.0, Apache ORC 1.8.5 will skip the API docs step completely, @guiyanakuang .

So I should follow the tutorial and commit the 1.8.4 api docs to the main branch as well, just like 1.8.3, I want to double check :)

**Comment by dongjoon-hyun** [comment]
Thank you! Yes. And, could you close this issue as the final piece, @guiyanakuang ?

**Comment by dongjoon-hyun** [comment]
Bravo for your first release, @guiyanakuang !

**Comment by dongjoon-hyun** [comment]
Oh, I missed to hand over this. You should create `v1.8.4` additionally like the following.

https://github.com/apache/orc/releases/tag/v1.8.3

**Comment by guiyanakuang** [comment]
I added the release tag for 1.8.4. https://github.com/apache/orc/releases/tag/v1.8.4
Thanks for the careful check, @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
My pleasure. I'm happy to cowork with you.
