### ISSUE TITLE
Problem when building orc cross platform

### ISSUE THREAD

**Issue by santrancisco** [apache/orc#1534]
Hi team, 

While trying to update our fork of orc, I ran into an issue where apache/orc is built successfully for some architects, but fails at others and the culprit seems to be this part here 

https://github.com/apache/orc/blob/f2c191f9653a5ddbca016e024ca0fb61508f5eeb/c%2B%2B/src/CpuInfoUtil.cc#L475 

The error is `/build/contrib/orc/c++/src/CpuInfoUtil.cc:475:12: error: use of undeclared identifier 'ArchParseUserSimdLevel'` and from looking at the code, correct me if i'm wrong but it seems ArchParseUserSimdLevel is only set when CPUINFO_ARCH_X86 is defined and thus undeclared identifier is thrown for all other architects?

**Comment by dongjoon-hyun** [comment]
Thank you for reporting, @santrancisco .

cc @wgtmac , @stiga-huang

**Comment by wgtmac** [comment]
@wpleonardo Do you have time to take a look?

**Comment by wpleonardo** [comment]
> @wpleonardo Do you have time to take a look?

Yes, I will take a look.

**Comment by dongjoon-hyun** [comment]
Is there any update about this issue?

**Comment by wpleonardo** [comment]
> Is there any update about this issue?

Sorry for late, I have something on hands, and I will try to fix this issue tomorrow. Thanks!

**Comment by dongjoon-hyun** [comment]
No problem at all. Thank you for checking this. Take your time~

**Comment by wpleonardo** [comment]
Just created PR https://github.com/apache/orc/pull/1542 to fix this issue. Thanks.
@wgtmac @dongjoon-hyun

**Comment by wgtmac** [comment]
> Just created PR #1542 to fix this issue. ORC build to succeed on my own local ARM platform. Thanks. @wgtmac @dongjoon-hyun

@santrancisco Do you have time to try it?

**Comment by santrancisco** [comment]
I can confirm now that the fix for both ARM and PPC work and we were able to compile apache/orc in our cicd. Thanks @wpleonardo  for your work!  Wish i could actually buy you a beer but here is a virtual one 🍺  :)

**Comment by wgtmac** [comment]
Thanks @santrancisco for confirmation!

I just merged it. Should we include it in the 1.9 release? @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
+1 for 1.9. Thank you!

**Comment by dongjoon-hyun** [comment]
I backported ORC-1447 to `branch-1.9`. Thank you all for reporting and fixing this .
