### ISSUE TITLE
SIGSEGV When read statistics of an all null boolean stripe.

### ISSUE THREAD

**Issue by oushu1zhouzhanghua1** [apache/orc#1556]
orc-statistic is a tool using Apache Orc Reader[C++] to get statistics of orc file, 
and I got a SIGSEGV when processing a stripe with an all null boolean columns.

When BooleanColumnStatisticsImpl::toProtoBuf, mutable_bucketstatistics() is called.
https://github.com/apache/orc/blob/0aba9875be4396c40adedae5a257e622d43b64eb/c%2B%2B/src/Statistics.hh#L463

The Protocol Buffers Docs[https://protobuf.dev/reference/cpp/cpp-generated/] saying:
```
Bar* mutable_foo(): Returns a pointer to the mutable Bar object that stores the field’s value. If the field was not set prior to the call, then the returned Bar will have none of its fields set (i.e. it will be identical to a newly-allocated Bar). After calling this, has_foo() will return true and foo() will return a reference to the same instance of Bar.
```

So in  BooleanColumnStatisticsImpl::BooleanColumnStatisticsImpl, https://github.com/apache/orc/blob/0aba9875be4396c40adedae5a257e622d43b64eb/c%2B%2B/src/Statistics.cc#L201, pb.has_bucketstatistics() is true. But pb.bucketstatistics().count(0) will access to a invalid field.

**Comment by wgtmac** [comment]
Thanks for reporting the issue! Would you like to create a PR with a fix?

**Comment by oushu1zhouzhanghua1** [comment]
> Thanks for reporting the issue! Would you like to create a PR with a fix?

ok

**Comment by wgtmac** [comment]
Do you have an JIRA account? You may need to create an [JIRA](https://issues.apache.org/jira/projects/ORC/issues/) first and submit an PR linking to the JIRA title. @oushu1zhouzhanghua1

**Comment by dongjoon-hyun** [comment]
Which Apache ORC versions are affected by this, @oushu1zhouzhanghua1 ?

**Comment by dongjoon-hyun** [comment]
Gentle ping, @oushu1zhouzhanghua1 .

**Comment by dongjoon-hyun** [comment]
Since there is not much activity, let's close this issue. I hope Java-version `orc-tools` can help the situations, @oushu1zhouzhanghua1 .
