### ISSUE TITLE
How to use the bloomfilter in orc format

### ISSUE THREAD

**Issue by Aitozi** [apache/orc#1576]
I want to test a value whether is in one orc file by the bloom filter, if in I want to load the file and cache the entire file for later lookup. However, it seems not have an interface like `BloomFilterReader` in parquet for using the internal bloom filter. Are there some good way to achieve this ?

thanks

**Comment by dongjoon-hyun** [comment]
Thank you for filing issues, @Aitozi . May I ask what is your use case?

**Comment by Aitozi** [comment]
@dongjoon-hyun Thanks for your quick response. I'm exploring to leverage the BloomFilter to speed up the [`lookup`](https://paimon.apache.org/docs/master/concepts/primary-key-table/#lookup) in Paimon compaction process. 

i want to judge the key in or not in a orc file by the min/max statistics and bloomfilter. If in, I will load the orc file to build a file cache for further lookup. However, bloomfilter in orc format seems not accessible outside the reader, Can you give me some suggestion here ?

**Comment by wgtmac** [comment]
> @dongjoon-hyun Thanks for your quick response. I'm exploring to leverage the BloomFilter to speed up the [`lookup`](https://paimon.apache.org/docs/master/concepts/primary-key-table/#lookup) in Paimon compaction process.
> 
> i want to judge the key in or not in a orc file by the min/max statistics and bloomfilter. If in, I will load the orc file to build a file cache for further lookup. However, bloomfilter in orc format seems not accessible outside the reader, Can you give me some suggestion here ?

Apache Iceberg has supported this. Please check this for more information: https://github.com/apache/iceberg/issues/5218

**Comment by dongjoon-hyun** [comment]
Hi, @Aitozi . Did you solve your problem?

I guess the original question was an lookup API which currently we don't provide.

Like Apache Iceberg, Apache Spark also provides only a high-level usage documentation.
- https://spark.apache.org/docs/latest/sql-data-sources-orc.html#bloom-filters
```SQL
CREATE TABLE users_with_options (
  name STRING,
  favorite_color STRING,
  favorite_numbers array<integer>
)
USING ORC
OPTIONS (
  orc.bloom.filter.columns 'favorite_color',
  orc.dictionary.key.threshold '1.0',
  orc.column.encoding.direct 'name'
)
```

**Comment by dongjoon-hyun** [comment]
Let me close this.
