### ISSUE TITLE
CMAKE linker error for snappy

### ISSUE THREAD

**Issue by abdulwadood97** [apache/orc#1613]
Whenever I try to compile using "make package" within build directory. it gives this error in "nappy_ep-build-err.log"
"
snappy_unittest.cc:(.text+0x680b): undefined reference to `testing::Message::Message()'
snappy_unittest.cc:(.text+0x6836): undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)' ,,,,,,
"
Can you please help me fix it? I see it has something to do with the gtest library. either its not linked or is not included.

Earlier like a month or two before it was working fine

**Comment by dongjoon-hyun** [comment]
Hi, @abdulwadood97 . Could you describe your environment your procedure?

Apache ORC maintains GitHub Action test coverage and we don't see any compilation failures in Ubuntu/Mac/Windows
- https://github.com/apache/orc/blob/main/.github/workflows/build_and_test.yml
- https://github.com/apache/orc/actions?query=branch%3Amain+event%3Apush

![Screenshot 2023-09-12 at 10 42 29 PM](https://github.com/apache/orc/assets/9700541/be97a4de-5604-429f-8c53-1fe7bd76d8a4)

**Comment by abdulwadood97** [comment]
I am using ubuntu 18.04.2 and linux kernel 5.4.0-49-generic for c++ only with AVX. 
The steps are as mentioned in the readme.
1. Clone.
2. Export the avx variable
3. make build dir
4. cmake run
5. then make package (it fails here)

**Comment by wgtmac** [comment]
Is there any change of gtest/gmock in your local environment? Make sure they are not in the path for linking.

**Comment by deshanxiao** [comment]
@abdulwadood97 Actually I encountered a similar problem when I upgrade OS from ubuntu18.04 to ubuntu20.04 using ubuntu official installer with the option "remain old packages".  I can work well after I deleted and reinstalled these compression library in ubuntu. Hope this can help you.

As @dongjoon-hyun mentioned, we won't maintain images in EOF. It's better to upgrade your OS.

**Comment by dongjoon-hyun** [comment]
Thank you for the useful tips, @deshanxiao .

**Comment by benjamin-j-c** [comment]
If you want to avoid removing conflicting libraries, you can modify snappy's cmake to not include system path:

`build/snappy_ep-prefix/src/snappy_ep/CMakeLists.txt:40 to 45`:
```cmake
find_package(GTest QUIET NO_CMAKE_SYSTEM_PATH)
if(GTEST_FOUND)
  set(HAVE_GTEST 1)
endif(GTEST_FOUND)

find_package(Gflags QUIET NO_CMAKE_SYSTEM_PATH)
```
