### ISSUE TITLE
orc.bloom.filter.columns=? (struct<f:

### ISSUE THREAD

**Issue by neopaf** [apache/orc#1644]
```sql
CREATE EXTERNAL TABLE test
(
    `data`   struct<request :struct<analyticCharacteristic :array<struct<id:string>>>>
```

Upon reading  org.apache.orc.OrcUtils#includeColumns I got the impression that
```
orc.bloom.filter.columns=data.request.analyticCharacteristic.id
```
will not work :(

Any ideas on how to allow bloom filter for that `id`?

**Comment by neopaf** [comment]
Reading same code I feel that
```
orc.bloom.filter.columns=*
```

Might work, but it would enable bloom filter for ALL columns, which is too much.

**Comment by guiyanakuang** [comment]
@neopaf, I think org.apache.orc.OrcUtils#includeColumns will work. You can run this test code.
```java
  @Test
  public void test() {
    TypeDescription typeDescription = TypeDescription.fromString(
        "struct<data:struct<request:struct<analyticCharacteristic:array<struct<id:string>>>>>");
    boolean[] booleans = includeColumns("data.request.analyticCharacteristic.id", typeDescription);
    for (boolean aBoolean : booleans) {
      System.out.print(aBoolean + " ");
    }
  }
```
Print results "false false false true true true"

The index number of id is 5, true means that we support creating Bloom filter for it

**Comment by neopaf** [comment]
looks perfect. sorry for not testing this thoroughly myself first.

**Comment by neopaf** [comment]
@guiyanakuang dear Yiqun, please suggest some good reading material as to how array's are mapped to columns?
I've very confused.
"index number of id is 5" is a mystery to me as of now :(

1. data
2. .request
3 .analyticCharacteristic
4. **array<** here (I feel this is the key
5. .id

I'm also confused about number of columns  -- we got 6 columns, which I don't get as well.

Please enlighten me?

**Comment by guiyanakuang** [comment]
You can check out this doc https://orc.apache.org/docs/types.html.

Even if the table creation statement only has a data column, the top-level root implicitly creates a struct.

Columns:

1. root struct
2. data struct
3. request struct
4. analyticCharacteristic  array
5. struct
6. id

**Comment by neopaf** [comment]
@guiyanakuang thanks for the doc link and root-structure explanation.
A bit fog left in "array" part:
>  Lists always have a single child column for the element values

Regretfully I don't get it :(
Simplifying:
* data: array<v:int>

I understand it this way:
1. root structure
2. data array 
3. v

Yet I'm still in the dark as to how array is stored:

Records:
* 1
* 2

Storage columns
1. something about root structure << what is here?
2. something about array << what is here?
3. [1,2] packed according to selected method (may it be DIRECT, DICTIONARY, or what was decided)

Maybe there is a good reading material on this?

(thanks a ton, for helping!)

**Comment by guiyanakuang** [comment]
@neopaf. I can’t find any relevant reading material either. At the moment it seems that looking at the source code is the most direct way to go.

https://github.com/apache/orc/blob/24beffb6fed6d408e25654e53c255f564c8bd8a9/java/core/src/java/org/apache/orc/impl/writer/ListTreeWriter.java#L78-L93

This is the writing process of array column.

83: Record array length
84: Write child column

The `array` column records the length of the array `lengths`. When reading `v` sequentially, we can assemble the array according to how many `v` are taken according to `lengths`.

You can look at StructTreeWriter and other writers to see how this is stored.

**Comment by neopaf** [comment]
@guiyanakuang came across this quick description: https://orc.apache.org/specification/ORCv0/

Looks like I had a total misconception inside my head that if we have an array the rows should somehow be duplicated, not at all!

Disc data structure allows for storing nested information, and column index is just an arbitrary assigned (most probably left-to-right, depth first) value. 

As you wrote: "write child column". One should not think about it as literally a column, just a value, no matter how complex (struct/array/whatever).

Upon reading the magic goes in reverse -- one gets to proper complicated structure and it gets unwound back to whatever detail we need.

Russian dolls.

Thanks again for pushing me in the right direction!
