### ISSUE TITLE
ORC-1100: Support `vcpkg`

### ISSUE THREAD

**Issue by dongjoon-hyun** [apache/orc#1659]
There exists a request from Apache Arrow community for Apache ORC community to support vcpkg.

https://vcpkg.io/en/index.html
 

Mailing List

https://lists.apache.org/thread/l3wjm2r6l57pz1q3o7wx57zvgzh7nxgl
 

Arrow community

https://github.com/apache/arrow/pull/12220#issuecomment-1019343606

**Comment by dongjoon-hyun** [comment]
This is removed from `Milestone 2.0.0`.

**Comment by deshanxiao** [comment]
Hi @dongjoon-hyun I check the [vcpkg list](https://vcpkg.io/en/packages) and it shows that ORC 1.9.1 has been supported. Could you explain this task in detail? Is this to support ORC2.0?


![image](https://github.com/apache/orc/assets/42019462/46aa8566-ca36-4dc7-afdc-0afbcc63541b)

**Comment by dongjoon-hyun** [comment]
Thank you for taking a look at this. I copied the JIRA content and pasted into this issue description.

IIUC, the existing one is done by Arrow community instead of ORC community. They asked us to do by ourselves during the Apache ORC release process.

**Comment by dongjoon-hyun** [comment]
BTW, do you know how to update it with our latest ORC 1.9.2? Can we document it in our website for next release managers?

- https://downloads.apache.org/orc/orc-1.9.2/

**Comment by deshanxiao** [comment]
@dongjoon-hyun We should make a PR to [microsoft/vcpkg](https://github.com/microsoft/vcpkg)
Here is the last one https://github.com/microsoft/vcpkg/pull/34026

**Comment by deshanxiao** [comment]
I'd be happy to add this documentation soon.

**Comment by dongjoon-hyun** [comment]
It's great. Thank you, @deshanxiao !

**Comment by dongjoon-hyun** [comment]
Let me include this topic back to `Milestone 2.0.0`.

**Comment by deshanxiao** [comment]
Add a link to support ORC v1.9.2 https://github.com/microsoft/vcpkg/pull/36098

cc @dongjoon-hyun @wgtmac

**Comment by deshanxiao** [comment]
We may consider removing the unofficial tag in the future.

```
orc provides CMake targets:

    find_package(unofficial-orc CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::orc::orc)

```

**Comment by wgtmac** [comment]
Thanks @deshanxiao and @dongjoon-hyun!

```
orc provides CMake targets:

    find_package(unofficial-orc CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::orc::orc)
```

BTW, where is this?

**Comment by dongjoon-hyun** [comment]
`vcpkg` has that in the orc `usage`, @wgtmac .
- https://github.com/microsoft/vcpkg/blob/master/ports/orc/usage
```
orc provides CMake targets:

    find_package(unofficial-orc CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::orc::orc)
```

And, `vcpkg` code itself publishes like this.
- https://github.com/microsoft/vcpkg/blob/c9919121dde6f61c0436adda94624636e041226b/ports/orc/portfile.cmake#L55-L59
```
vcpkg_cmake_config_fixup(PACKAGE_NAME unofficial-orc)
vcpkg_copy_pdbs()

file(READ "${CURRENT_PACKAGES_DIR}/share/unofficial-orc/unofficial-orc-config.cmake" cmake_config)
file(WRITE "${CURRENT_PACKAGES_DIR}/share/unofficial-orc/unofficial-orc-config.cmake"
```

**Comment by dongjoon-hyun** [comment]
Also, cc @williamhyun , too.

**Comment by dongjoon-hyun** [comment]
BTW, FYI, I filed your account request form, @deshanxiao . Since the desired ID was not provided on the ICLA, the creation is slipped from the secretary to the ORC PMC Chair. And, it seems that PMC Chair seems to be busy, so I filed your form because I can do that as the ASF member.
- https://infra.apache.org/managing-committers.html
```
Encourage your new committer to include both the PMC and the desired account id on the submitted ICLA
so the secretary or assistant filing the ICLA can request the account.
If the new account information is not provided on the ICLA,
the PMC chair is responsible for getting the new committer's desired account ID and requesting the new account.
Use the [New Account Request form](https://whimsy.apache.org/officers/acreq) on Whimsy.
Should the PMC chair be unavailable for any reason, any ASF member can use the same form in their stead.
```

**Comment by deshanxiao** [comment]
Great! Thank you @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Hi, @deshanxiao . 

For this issue (ORC-1100), could you try to make a webpage PR to add a new section about `vcpkg` at this file?
- https://github.com/apache/orc/blob/main/site/develop/index.md

And, after the ASF ID creation, you need to update this page.
- https://github.com/apache/orc/blob/main/site/develop/committers.md

**Comment by deshanxiao** [comment]
Hi @dongjoon-hyun I will update the web page tomorrow since I am going to hospital today. :)

**Comment by dongjoon-hyun** [comment]
Sure. Take a good care~
> I will update the web page tomorrow since I am going to hospital today. :)

This is resolved via https://github.com/apache/orc/commit/395b8a958454ef68d183eb6d4578626a0c818944

**Comment by dongjoon-hyun** [comment]
To @deshanxiao , your ID was created successfully.
- https://whimsy.apache.org/roster/committer/deshanxiao

Additionally, I promoted your JIRA account to ORC JIRA committer group too.

**Comment by dongjoon-hyun** [comment]
Please make a PR to add you to the committer page like the following. Then, you can test your committership by merging by yourself, @deshanxiao .
- #1405
