### ISSUE TITLE
one compression block not allow to bigger than 8M

### ISSUE THREAD

**Issue by ljyss9** [apache/orc#1727]
compress block header size is 3 byte to store compressed size，if length more than 8M，will overflow

**Comment by dongjoon-hyun** [comment]
Thank you for reporting. Could you provide your reproducible procedure, @ljyss9 ?

**Comment by ljyss9** [comment]
Just use csv-import tool can reproduce it，set compression chunk size to 64M, and input data is hard to compress，once one block after compress is larger than 8M，will cause orc data wrong.

**Comment by wgtmac** [comment]
That's definitely something we need to fix.

**Comment by dongjoon-hyun** [comment]
To @ljyss9 

1. This is not a reproducible procedure.
> input data is hard to compress

2. Do you mean that you hit orc-tool failure? Or, `orc-tool` succeeded but the generated file is corrupted?
> will cause orc data wrong.

**Comment by deshanxiao** [comment]
@ljyss9 which codec did you use? If possible, can all codecs reproduce this problem?

**Comment by ljyss9** [comment]
@dongjoon-hyun 
orc-tool succeeded but the generated file is corrupted
This picture is copy from official website, what the behavior is if the compressed block length is greater than 3 bytes.
![image](https://github.com/apache/orc/assets/16235177/d0d57823-d00f-4726-a22d-ea8f0b907288)

**Comment by ljyss9** [comment]
@deshanxiao 
all codecs  can reproduce this problem

**Comment by cxzl25** [comment]
In [ORC-238](https://issues.apache.org/jira/browse/ORC-238) (version 1.5.0), an assert for buffer size is added, and there should be no problem with buffer size exceeding 8M.

Can you provide the version and command you used? @ljyss9

https://github.com/apache/orc/blob/803e273cd5cd7eff3cb34e8595f595a278bc8823/java/core/src/java/org/apache/orc/impl/OutStream.java#L201-L213

**Comment by deshanxiao** [comment]
I think I understand @ljyss9‘’s issue.

Although like @cxzl25 mentioned, we have relevant restrictions on the java side. But csv-import (c++ side) still has the issue which means there is no limitation on the c++ side. 

As for the condition that data must be difficult to compress. It is just to keep the original data in the block because ORC will not save compressed data once it is found that compression is not cost-effective.

Therefore, the final solution is that once the C++ side finds that the compression chunk size exceeds 8M value, it will refuse to write any data like Java side.

**Comment by wgtmac** [comment]
@deshanxiao Thanks for the update! Could you please provide a link to the protection code on the Java side? I think the C++ code should do the same thing.

**Comment by deshanxiao** [comment]
Hi @wgtmac Actually @cxzl25 has provided the code on the Java side:

https://github.com/apache/orc/blob/8f22732bfe336ece7d7bcfade3ca6d200d276f1c/java/core/src/java/org/apache/orc/impl/OutStream.java#L201-L213

**Comment by wgtmac** [comment]
cc @ffacs

**Comment by ffacs** [comment]
Thank you, @ljyss9. I will make a patch to forbid invalid compression block size in writer options later.

**Comment by dongjoon-hyun** [comment]
This is resolved via ORC-1602 (Apache ORC 1.9.3 and 2.0.0).
