### ISSUE TITLE
In cpp/java sdk, SearchArgument looks like didn't use the footer and stripe stats.

### ISSUE THREAD

**Issue by Smith-Cruise** [apache/orc#1798]
I've checked about the code, but it looks like we only use row group's index in SearchArgument, do I missing something?

Why do we only use row group's index?

**Comment by wgtmac** [comment]
C++ reader has leveraged the stripe stats. Please check https://github.com/apache/orc/blob/main/c++/src/Reader.cc#L1062-L1066 for reference.
