### ISSUE TITLE
Release ORC 2.0.2

### ISSUE THREAD

**Issue by dongjoon-hyun** [apache/orc#1992]
- [x] GitHub Action CI Check.
   - https://github.com/apache/orc/actions/workflows/build_and_test.yml?query=branch%3Abranch-2.0
- [x] [Apache Spark 4.0.0 Integration Test with 2.0.2-SNAPSHOT](https://github.com/dongjoon-hyun/spark/pull/15)
- [x] [Vote Tag Creation](https://github.com/apache/orc/releases/tag/v2.0.2-rc0)
- [x] [Upload RC0 Vote Artifacts](https://dist.apache.org/repos/dist/dev/orc/v2.0.2-rc0/)
- [x] [Upload to ASF Maven Central](https://repository.apache.org/content/repositories/orgapacheorc-1083)
- [x] [Send RC0 Vote Email](https://lists.apache.org/thread/nf6kppjf16vj6b3j28osxcj125hf4lz9)
- [x] [Apache Spark 4.0.0 Integration Integration Test with RC0](https://github.com/dongjoon-hyun/spark/pull/16)
- [x] [Send RC0 Vote Result](https://lists.apache.org/thread/c7hb5chb23y1t68rbmzn7sfo8fyd8ptv)
- [x] [Publish to Apache Download](https://dist.apache.org/repos/dist/release/orc/orc-2.0.2/)
- [x] [Release Tag Creation](https://github.com/apache/orc/releases/tag/v2.0.2)
- [x] [Publish to Maven Central](https://repository.apache.org/content/repositories/releases/org/apache/orc/orc-core/2.0.2/)
- [x] Create next milestone
- [x] Register `2.0.2` to https://reporter.apache.org/addrelease.html?orc

**Comment by cxzl25** [comment]
The `Send RC0 Vote Email` link is for 2.0.1, I fixed it now.

**Comment by dongjoon-hyun** [comment]
Oops. Thank you, @cxzl25 !
