### ISSUE TITLE
AVX512 is enabled by default in ORC's Conan Recipe

### ISSUE THREAD

**Issue by yuedai** [apache/orc#2015]
In the default ORC Conan Recipe, AVX512 is enabled, which can cause compatibility issues on many AMD CPUs. Could we consider setting the default value of "build_avx512" to False?

Link to the relevant code: 

https://github.com/apache/orc/blob/3e07b3f8f8cee5a32c4a7747d9a70df9deea5211/conan/all/conanfile.py#L50

**Comment by yangzhg** [comment]
+1

**Comment by kexianda** [comment]
+1

**Comment by wgtmac** [comment]
It might be better to directly create an issue or submit a pr against conan center. Here we simply mirror the script from upstream.
